site_name: Clah Documentation
site_url: https://github.com/esposimo/clah
repo_url: https://github.com/esposimo/clah
site_description: Official Clah Documentation

nav:
  - Home: index.md
  - Install:
    - Requirements: ./install/requirements.md
    - Getting Started!: ./install/getting-started.md
    - Service Config: ./install/sc-install.md
    - Network: ./install/network.md
    - Vault: ./install/vault.md
  - Service Config:
    - Put and Get information: ./service-config/put-get-sc.md
    - Infrastructure path: ./service-config/infra-path-sc.md
  - Manage Secrets:
    - How to use SOPS: ./vault/how-use-sops.md
    - Works with KV: ./vault/create-kv.md
  - Platforms:
    - Terraform: ./platforms/terraform.md
    - Docker: ./platforms/docker.md
    - SOPS: ./platforms/sops.md
  - CLAH cli:
    - Usage: ./cli/clah-command.md
    - sc: ./cli/cli-sc.md
    - sops: ./cli/cli-sops.md
  - About: about.md

theme:
  features:
    - navigation.tabs
    - navigation.path
  name: material
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition

plugins:
- search
- mkdocstrings
- open-in-new-tab:
    add_icon: true
