site_name: Clah Documentation
site_url: https://github.com/esposimo/clah
repo_url: https://github.com/esposimo/clah
site_description: Official Clah Documentation

nav:
  - Home: 'index.md'
  - Install:
    - Requirements: requirements.md
    - Getting Started!: 'getting-started.md'
    - Initialize SC: sc-install.md
    - Network: network.md
    - Vault: vault.md
  - Service Config:
    - Put and Get information: put-get-sc.md
    - Infrastructure path: infra-path-sc.md
  - Manage Secrets:
    - How to use SOPS: how-use-sops.md
    - Works with KV: create-kv.md
  - Platforms:
    - Terraform: terraform.md
    - Docker: docker.md
    - SOPS: sops.md
  - CLAH cli:
    - Usage: clah-command.md
    - sc: cli-sc.md
    - sops: cli-sops.md
  - About: 'about.md'

theme:
  features:
    - navigation.tabs
    - navigation.path
  name: material
  features:
    - content.code.copy
    - content.code.select
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: green
      accent: orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: green
      accent: orange
      toggle:
        icon: material/brightness-4
        name: Switch to system preference
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.details
  - admonition

plugins:
- search
- mkdocstrings
- open-in-new-tab:
    add_icon: true
